title: Peter Huszar # your name (or website title) here
logo: "/images/profile_picture_circular.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated as an MSc electrical engineer. I worked as a software developer in the recent years. I am doing my PhD while working, My research is focuses on the application of unmanned aerial vehicles. I have more than 3 years of experience in the aerospace industry of which 1 year was at the German Aerospace Center (DLR). I have expertise in both software and hardware development. I regularly give presentations on conferences and publish my articles.
  <p><a></a>
  </p>
  <a href="./pdf/peter_huszar_cv_eng_2021_01_27.pdf">Download My CV</a>
  <br/>
  <a href="https://www.linkedin.com/in/huszar-peter/">LinkedIn Profile</a>
  <br/>
  <a href="https://peterhuszar.medium.com/">Medium Blog</a>
  <br/>
  <a href="https://www.researchgate.net/profile/Peter_Huszar2/">ResearchGate</a>
  <br/>
  <a href="https://orcid.org/0000-0001-6169-3777">ORCID</a>
  <br/>
  <a href="https://doktori.hu/index.php?menuid=192&sz_ID=30258&lang=EN">ODT</a>
  <br/>

  
theme: jekyll-theme-minimal
google_analytics: UA-187198908-1 # your Google Analytics tracking ID here
